### PR TITLE
feat: Bump `zksync-protocol` to 0.150.6

### PR DESCRIPTION
**Pull request by 0xVolosnikov**
# What ❔

## Checklist

- [ ] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] Code has been formatted via `zk fmt` and `zk lint`.

### CODE REVIEW

**Comment by 0xVolosnikov** [comment]
@EmilLuta I don't think so. 
@robik75 could you please help with debugging (I do not have a local setup to check it)? Looks like the failing test is in shivini:
`test::zksync::compare_proofs_for_all_zksync_circuits`

**Comment by 0xVolosnikov** [comment]
Most likely we need to update some test artifacts

**Comment by robik75** [comment]
The test should not fail but this looks more like some problem with the runner then the code itself, I restarted the job.

**Comment by robik75** [comment]
It failed again, I will try to run it locally.

**Review by robik75 — APPROVED** [review]

**Pull request merged**
